-- AUTO-GENERATED by scripts/generate_seed.py — do not edit by hand.
-- Seeds concept_families + creatives from the Outlier sheet, into the
-- 'outlier' org (see supabase/migrations/0015_organizations.sql). This script
-- only ever seeds one org at a time, so concept_family_id lookups below are
-- unscoped by org_id — safe here since a single run never has two orgs
-- sharing family names, but not a pattern to copy elsewhere.

with org as (select id from public.organizations where slug = 'outlier')
insert into public.concept_families
  (org_id, name, archetype, narrative, audience, strategic_intent, proven_hook_formula, is_proven, compliance_note)
select org.id, v.name, v.archetype::archetype_type, v.narrative, v.audience, v.strategic_intent, v.proven_hook_formula, v.is_proven, v.compliance_note
from org, (values
  ('Parlay', 'Broad-appeal', 'The most popular bet and the most heartbreaking — parlays die on a single leg. Speak to the parlay bettor who keeps coming agonizingly close, then broaden to parlay bettors generally: building smarter parlays, knowing which legs to trust. Sub-angles: weak-leg vetting, loss-aversion (''stop losing parlays''), and big parlay cashes earned through research.', 'Parlay bettors — a large, mainstream, emotionally-invested segment chasing the multi-leg payout and loss-averse about near-misses.', 'Top-of-funnel volume. Your single highest-spend hook. Run broadly across sports.', '''This is exactly how a bettor turned a $X parlay into over $Y'' → reveal the favorable-matchup research behind it (filter by opponent rank, stat-backed legs) → 7-day trial. (NFL $100→$50K proven.)', true, null),
  ('Don''t Use', 'Qualifier', 'A pattern-interrupt that challenges the inferior research method the target already relies on — betting off ''last 5 games,'' a free stat site, surface-level numbers — and shows why it leads them wrong. Positions Outlier as the deeper, correct way.', 'Bettors who ALREADY do light research with the wrong inputs or tools. They think they''re informed; their method is shallow.', 'Highest-scaling qualifier in your library. Filters for serious bettors who convert efficiently.', '4-beat: ''Stop using [wrong method]…'' → WHY it''s wrong (every game has new matchups, injuries, lineups) → THE FIX (Outlier pulls sportsbook lines, odds, historic data) → 7-day trial. (~$77.5K, your #1 scaler.)', true, 'COMPLIANCE: attack the METHOD (last-5, free stat sites, surface numbers) — do NOT name a specific competitor app unless Outlier approves it in writing. The top ad named PrizePicks; we''ve stripped it pending sign-off.'),
  ('Big Win', 'Broad-appeal', 'Real results as social proof. Someone used Outlier''s research and cashed — shown as the OUTCOME OF A PROCESS. ''Here''s the hit — and here''s the research behind it.''', 'Aspirational, FOMO-driven broad audience that wants to believe the win is repeatable through research.', 'Highest combined CTR + quality score in your data. The reliable volume workhorse. Scale lever = swap the $amount and the player on a fixed template.', '''This is exactly how a bettor turned a $X parlay into over $Y'' over a real slip → the research that built it → 7-day trial. (~$35.7K, your top single variant.)', true, 'COMPLIANCE: ''$X into $Y'' framing is PRESERVED (proven scaler) but pushes the no-win/ROI-guarantee rule — Zaire is raising this with the client on the call. Always show the process behind the win.'),
  ('How-To', 'Qualifier', 'Show, don''t tell. A quick over-the-shoulder of the actual research workflow — open the app, filter, surface one stat-backed pick. Demonstrates the product and the exact behavior that predicts conversion.', 'Curious, serious bettors who want to see how it works before committing.', 'Efficient low-CPT educational content; doubles as a research-to-bet-loop demo.', '''This is exactly how I [win more NBA bets / research X]…'' → open Outlier, filter, show ONE stat-backed pick (e.g. ''hit this line in 75% of H2H matchups'') → 4.9 stars / 7-day trial.', true, null),
  ('Gamescript', 'Qualifier', 'Foresight. ''I knew this was going to happen — because the data told me.'' Reading a game''s narrative, a player''s spot, or a rest situation BEFORE it unfolds. A confident, absolute ''I called it because I had the context'' tone. (The Wemby player-prop ad lives here, not in Props — it''s a foresight ad.)', 'More advanced bettors who pride themselves on reading the game and the spot, not just the box score.', 'Positions Outlier as the pre-game read that hands you the script in advance. NBA-proven; extend to other sports.', '''I knew [player] was going over [line] because Outlier showed me the data'' → the specific proof stat (hit 7 of last 10; dominates bottom-10 teams) → 7-day trial. (Wemby ~$19K; Amen rest-filter proven.)', true, null),
  ('Stop Betting Blind', 'Broad-appeal', 'The thesis-level case for using data AT ALL. ''Betting without data is just donating money.'' Aimed at the bettor running on gut and vibes with no research — convert them to the very idea of researching.', 'The non-data bettor (vibes / gut). Earliest awareness stage — largest audience, least qualified.', 'Awareness-stage conversion. Outlier''s strongest validated language. Pulls vibes-bettors into the category.', null, false, null),
  ('One App / Consolidation', 'Mixed', 'You''re juggling four apps — a stats site, your book, X, a score app — and losing the line while you do it. Outlier collapses the whole research stack into one place.', 'Bettors who already research across multiple tools and feel the friction of switching.', 'Workflow-pain angle; supports the all-in-one + one-tap-deeplink value prop.', null, false, null),
  ('Data Edge', 'Qualifier', 'For bettors who ALREADY use data but are missing the DEEPER layer — matchup splits by scheme, injury/lineup context, line movement — the stuff the sportsbook and basic tools don''t surface. ''You''re researching, but not with THIS.''', 'The semi-informed bettor who thinks they have a handle but has an incomplete picture. Mid-funnel.', 'Distinction from Stop Betting Blind is AWARENESS STAGE: Stop Betting Blind converts non-users to the idea of data; Data Edge upgrades existing-data users to the deeper/hidden data. Same thesis, different audience. Merge if you''d rather run one data message.', null, false, null),
  ('Build a Process', 'Qualifier', 'Consistency comes from a repeatable system, not hot picks. Save filters, build a routine, let the research compound. ''Casuals guess; consistent bettors have a process.''', 'Bettors who want to level up, plus serious users who value consistency.', 'Tied to Outlier''s own research: users who build a workflow retain far better. Supports the client''s stated goal of increasing user quality and fighting churn — value beyond CPT.', null, false, null),
  ('Demystify', 'Broad-appeal', 'The data looks intimidating, but it''s actually three taps. Make depth feel simple and approachable; lower the perceived barrier to entry.', 'Intimidated or casual bettors who''d benefit but assume the tool is too advanced for them.', 'Counters Outlier''s #2 churn reason (''too complex''). Education-first, approachable tone.', null, false, null),
  ('Wildcard', 'Mixed', 'The R&D budget of the slate — deliberately new, unproven angles (anti-cappers, community-cast UGC, cross-sport, WNBA, line movement). Most will lose; the winners graduate into proven families next cycle.', 'Varies by experiment.', 'Keep a steady ~15% experimental allocation so the proven families always have a pipeline of fresh winners.', null, false, null),
  ('EV / Pro', 'Qualifier', 'For the EV-literate, advanced bettor: positive EV, sharp odds, arbitrage and middles. Pro-tier only.', 'Advanced / Pro bettors who already understand EV (creator and Discord-type audiences).', 'Highest-value users but a narrow audience.', null, false, 'COMPLIANCE: never lead with EV in broad acquisition (per the brief). Note: proven big-win ads mention ''plus-EV legs'' mid-script — also a client-call item. Keep EV gated to Pro / EV-literate placements.')
) as v(name, archetype, narrative, audience, strategic_intent, proven_hook_formula, is_proven, compliance_note)
on conflict (org_id, name) do nothing;

insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('01', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Parlay'),
   'Screen demo of a winning multi-leg slip; reveal the research (favorable opponent rank, stat-backed legs) behind it.', 'This is exactly how a bettor turned a $100 parlay into over $50,000.', 'Parlay + Big Win', 'Broad-appeal', 'Matchup data (opponent rank)', 'NFL', 'Screen demo', '✓ PROVEN template (NFL $100→$50K) — swap $amount + player + sport', 'Try 7 days free', true, null)
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('02', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Parlay'),
   'Same proven slip template, new number + player + sport.', 'This is exactly how a bettor turned a $50 parlay into six figures.', 'Parlay + Big Win', 'Broad-appeal', 'Matchup data (opponent rank)', 'NBA', 'Screen demo', 'Variant of proven $X→$Y template — swap amount/player/sport', 'Try 7 days free', true, null)
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('04', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Parlay'),
   'In-season MLB: the weak leg is the pitcher/park matchup; show the split.', 'Your MLB parlay''s weak leg is the pitcher.', 'Parlay', 'Broad-appeal', 'Matchup splits', 'MLB', 'Screen demo', 'In-season MLB swap', 'Research your next pick free', false, '2026-06-26')
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('06', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Don''t Use'),
   'Baseball re-skin: hitter''s L5 spike vs season/H2H baseline.', 'Last five games is lying to you.', 'Don''t-Use-Last-5', 'Qualifier', 'H2H / matchup splits', 'MLB', 'Screen demo', 'Sport swap (in-season)', 'Research your next pick free', false, '2026-06-26')
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('05', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Don''t Use'),
   'Screen-rec: pull a player''s L5 vs L20/season hit rates; 4-beat callout→why→fix→CTA.', 'Stop using the last five games to make your picks.', 'Don''t-Use-Last-5', 'Qualifier', 'Prop hit rates (L5/L10/L20)', 'NBA', 'Screen demo', '✓ PROVEN top scaler (~$77.5K). Real ad named PrizePicks — stripped pending client OK', 'See the data your sportsbook hides', true, null)
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('10', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Big Win'),
   'Same proven template, in-season MLB number + player.', 'This is exactly how a bettor turned $20 into $90,000.', 'Big Win', 'Broad-appeal', 'Matchup data', 'MLB', 'Screen demo', 'Variant of proven $X→$Y template — in-season MLB swap', 'Try 7 days free', true, '2026-06-26')
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('07', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Don''t Use'),
   'Challenge generic free stat sites/surface stats and show the deeper view they miss.', 'Free stat sites show you numbers. Not the right ones.', 'Don''t-Use-[Method]', 'Qualifier', 'Matchup splits / depth', 'Multi-sport', 'Talking head', 'Challenge a method (NO competitor name unless approved)', 'See the data your sportsbook hides', false, null)
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('08', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Don''t Use'),
   'Athlete-led: everyone''s tailing a star prop tonight; the real data disagrees.', 'Everyone''s tailing this prop. The data disagrees.', 'Player Props', 'Broad-appeal', 'Matchup splits', 'NBA', 'Athlete-focused', 'Athlete-led (CTR lift)', 'Research your next pick free', false, null)
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('14', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'How-To'),
   'Same workflow for baseball (in-season).', 'This is exactly how I research an MLB prop in 30 seconds.', 'How-To', 'Qualifier', 'Full workflow demo', 'MLB', 'Screen demo', 'Sport swap (in-season)', 'Try 7 days free', false, '2026-06-26')
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('24', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'One App / Consolidation'),
   'Fast screen-rec of the full loop: research a prop, compare books, deeplink to slip.', 'Research it. Compare it. Bet it. Two taps.', 'Research-Compare-Bet', 'Qualifier', 'One-tap deeplink', 'MLB', 'Screen demo', 'Deeplink / loop variant', 'Get it all in one app', false, '2026-06-26')
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('11', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Big Win'),
   'UGC: bettor shows a cash and walks the research that informed it.', 'I researched this one before I tailed it.', 'Big Win', 'Broad-appeal', 'Research-to-bet loop', 'Multi-sport', 'UGC', 'UGC personal-testimonial variant', 'Try 7 days free', false, null)
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('12', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Big Win'),
   'Outlier insights tab: a prop with an 80% hit rate backed by snap counts, red-zone trends, historic data.', 'Making money with Outlier is so easy.', 'Big Win / Proof', 'Broad-appeal', 'Insights tab (hit rate backed by data)', 'NFL', 'Screen demo', '✓ PROVEN (Zay) — insights-tab proof; swap player + stat', 'Try 7 days free', true, null)
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('13', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'How-To'),
   'Full workflow: open Outlier → NBA props → filter over, sort by opponent rank → show one stat-backed pick (75% H2H).', 'This is exactly how I''m going to win more NBA bets this season.', 'How-To', 'Qualifier', 'Full workflow demo', 'NBA', 'Screen demo', '✓ PROVEN — lead with a specific stat (75% H2H)', 'Try 7 days free', true, null)
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('32', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Demystify'),
   'Micro-lesson: one research habit, taught in ~10 seconds (education-first).', 'One research habit that changes how you bet.', 'Micro-Lesson', 'Broad-appeal', 'Single-feature teach', 'MLB', 'Talking head', 'Education-first format (creator lane)', 'Research your next pick free', false, '2026-06-26')
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('33', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Wildcard'),
   'Cross-sport bridge: your NBA research routine transfers straight to MLB.', 'Your NBA process works for MLB too.', 'Cross-Sport', 'Qualifier', 'Cross-sport saved filters', 'MLB', 'Screen demo', 'Retention insight', 'Build your betting process. Start free.', false, '2026-06-26')
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('16', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Gamescript'),
   'Player-prop foresight: I called the over because the data showed the matchup edge (hit 7 of last 10; dominates bottom-10 teams).', 'I knew this star was going over — Outlier showed me the data.', 'Gamescript / Foresight', 'Qualifier', 'Prop hit rates + matchup splits', 'NBA', 'Screen demo', '✓ PROVEN (~$19K) — re-tagged from Props; swap player + line + stat', 'Try 7 days free', true, null)
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('17', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Gamescript'),
   'Situational foresight: research a prop adjusting for days of rest using the rest filter.', 'This is exactly how I research props for days of rest.', 'Gamescript / Foresight', 'Qualifier', 'Situational / rest filter', 'NBA', 'Screen demo', '✓ PROVEN (Amen) — situational-filter foresight; swap player + situation', 'Research your next pick free', true, null)
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('18', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Gamescript'),
   'Game-level script: the pace/matchup data made the flow readable pre-game.', 'I knew this game would play out this way.', 'Gamescript / Foresight', 'Qualifier', 'Matchup / pace data', 'NBA', 'Screen demo', 'Game-level / over foresight', 'See the data your sportsbook hides', false, null)
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('19', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Stop Betting Blind'),
   'Flagship talking head on the #1 validated line; cut to data depth behind one bet.', 'Stop betting blind — that''s just donating money.', 'Stop-Betting-Blind', 'Broad-appeal', 'Data depth overview', 'Multi-sport', 'Talking head', 'Flagship (research #1 hook)', 'Start your free trial', false, null)
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('20', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Stop Betting Blind'),
   'A bet about to be placed with no matchup checked, then reveal the matchup view.', 'Betting this without the matchup? That''s blind.', 'Stop-Betting-Blind', 'Qualifier', 'Matchup splits', 'NBA', 'Screen demo', 'Matchup variant', 'See the data your sportsbook hides', false, null)
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('03', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Parlay'),
   'Loss-aversion cut: a busted parlay, then the public injury note that killed it.', 'Stop losing parlays to stuff you could''ve seen.', 'Loss Aversion', 'Broad-appeal', 'Injury reports', 'Multi-sport', 'Talking head', 'Loss-aversion sub-angle (proven ~$57K)', 'See the data your sportsbook hides', true, '2026-06-26')
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('22', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Stop Betting Blind'),
   'Talking head: reframe betting blind as donating money; lead into the fix.', 'Stop donating money to the books.', 'Stop-Betting-Blind', 'Broad-appeal', 'Data depth overview', 'Multi-sport', 'Talking head', 'Donating-money variant (refiled from Profit)', 'Start your free trial', false, null)
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('23', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'One App / Consolidation'),
   'Screen-rec montage: 4 apps (stats, book, X, score app) collapsing into one Outlier view.', 'Stop juggling 4 apps to bet one prop.', 'One-App', 'Broad-appeal', 'All-in-one / odds comparison', 'Multi-sport', 'Screen demo', 'Pillar 2 angle', 'Get it all in one app', false, null)
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('21', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Stop Betting Blind'),
   'Motion graphic: the stat that already told the story, ignored — now surfaced.', 'The numbers already told you. You didn''t look.', 'Stop-Betting-Blind', 'Broad-appeal', 'Prop hit rates', 'Multi-sport', 'Motion graphics', 'Data-was-there variant (refiled from Numbers)', 'See the data your sportsbook hides', false, '2026-06-26')
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('25', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Data Edge'),
   'Reveal matchup splits by opponent/defensive scheme the book never surfaces.', 'Your sportsbook hides this matchup data.', 'Data-Edge', 'Qualifier', 'Matchup splits', 'NBA', 'Screen demo', 'Upgrade existing-data users (Pillar 3)', 'See the data your sportsbook hides', false, null)
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('26', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Data Edge'),
   'A late injury/lineup change and how it flips the read on a prop.', 'One lineup change just flipped your bet.', 'Data-Edge', 'Qualifier', 'Injury / lineup reports', 'NBA', 'Screen demo', 'Injury variant', 'Research your next pick free', false, null)
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('27', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Data Edge'),
   'Same prop across multiple books, best price highlighted.', 'Same bet. Better price. Every book, one place.', 'Odds-Comparison', 'Broad-appeal', 'Real-time odds comparison', 'Multi-sport', 'Screen demo', 'Odds-comparison variant', 'Get it all in one app', false, null)
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('28', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Build a Process'),
   'Talking head: the difference between casual and consistent isn''t the picks, it''s the process.', 'Casuals guess. Consistent bettors have a process.', 'Build-a-Process', 'Qualifier', 'Saved filters + My Picks', 'Multi-sport', 'Talking head', 'Pillar 4 — ties to client churn/quality goal', 'Build your betting process. Start free.', false, null)
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('29', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Build a Process'),
   'Screen-rec: same saved filters every night, research done in 30 seconds.', 'Same filters, every night, 30 seconds.', 'Build-a-Process', 'Qualifier', 'Saved filters + alerts', 'NBA', 'Screen demo', 'Saved-filters variant', 'Build your betting process. Start free.', false, null)
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('30', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Build a Process'),
   'UGC: a green week shown as the output of a research routine, not luck.', 'This is what a researched week looks like.', 'Green Streak / Process', 'Broad-appeal', 'My Picks tracker', 'Multi-sport', 'UGC', 'Sustained-results variant (refiled from Green Streak)', 'Build your betting process. Start free.', false, null)
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('31', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Demystify'),
   'Show the ''intimidating'' data view, then collapse the whole research into 3 taps.', 'Sports betting research looks hard. It''s 3 taps.', 'Demystify', 'Broad-appeal', 'Full workflow demo', 'Multi-sport', 'Screen demo', 'Counters ''too complex'' churn', 'Try 7 days free', false, '2026-06-26')
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('35', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Wildcard'),
   'Anti-picks: tired of cappers selling picks? Do your own research.', 'Stop paying cappers. Do your own research.', 'Anti-Picks', 'Qualifier', 'Data depth overview', 'Multi-sport', 'Talking head', 'Differentiator (not a picks service)', 'See the data your sportsbook hides', false, '2026-06-26')
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('09', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Big Win'),
   'Screen demo of a winning slip; reveal the favorable-matchup research behind it (process, not promise).', 'This is exactly how a bettor turned a $5 parlay into over $270,000.', 'Big Win', 'Broad-appeal', 'Matchup data / research-to-bet', 'WNBA', 'Screen demo', '✓ PROVEN top variant (~$35.7K) — swap $amount + player', 'Try 7 days free', true, '2026-06-26')
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('34', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Wildcard'),
   'Authentic creator from the core community walking through how they actually research.', 'How I actually research before I bet.', 'Community / Identity', 'Broad-appeal', 'Full workflow demo', 'Multi-sport', 'UGC', 'Community-cast UGC', 'Try 7 days free', false, null)
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('15', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'How-To'),
   'What sharp bettors actually check before placing — quick guided tour.', 'This is exactly how sharp bettors research.', 'How-To', 'Qualifier', 'Full workflow demo', 'WNBA', 'Screen demo', 'Profitability framing', 'Build your betting process. Start free.', false, '2026-06-26')
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('36', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Wildcard'),
   'Line on the move from open to now, and the context behind it.', 'The line''s moving. Here''s what''s behind it.', 'Line-Movement', 'Qualifier', 'Line movement tracking', 'Multi-sport', 'Screen demo', 'Feature test', 'See the data your sportsbook hides', false, null)
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('37', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Wildcard'),
   'Motion graphic: cluttered betting apps swiped away, one app remains.', 'Delete your other betting apps.', 'One-App', 'Broad-appeal', 'All-in-one workflow', 'Multi-sport', 'Motion graphics', 'Provocative one-app', 'Get it all in one app', false, null)
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('38', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'Wildcard'),
   'WNBA in-season props angle — softer market if you research.', 'WNBA props are softer than you think.', 'Player Props', 'Qualifier', 'Prop hit rates', 'WNBA', 'Screen demo', 'In-season WNBA', 'Research your next pick free', false, '2026-06-26')
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('39', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'EV / Pro'),
   'Pro demo (EV-literate audiences only): Positive EV feed filtered to a strategy.', 'Positive EV, filtered to your strategy.', 'EV (Pro)', 'Qualifier', 'EV+ Power Feed', 'Multi-sport', 'Screen demo', 'Pro-gated (not broad acquisition)', 'Try 7 days free', false, null)
on conflict (sheet_id, org_id) do nothing;
insert into public.creatives
  (sheet_id, org_id, concept_family_id, content_summary, hook_line, hook_angle,
   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)
values ('40', (select id from public.organizations where slug = 'outlier'), (select id from public.concept_families where name = 'EV / Pro'),
   'Pro demo: a middle/arb the market left open (no outcome guarantees).', 'Two books. One number the market missed.', 'EV (Pro)', 'Qualifier', 'Arbitrage / Middle feed', 'Multi-sport', 'Screen demo', 'Pro-gated (not broad acquisition)', 'Try 7 days free', false, null)
on conflict (sheet_id, org_id) do nothing;
