#!/usr/bin/env python3
"""Generate supabase/seed.sql from the Outlier paid-media sheet.

One-off authoring tool: reads the Excel export and emits idempotent seed SQL for
concept_families + creatives. Re-run if the sheet changes.
Usage: python3 scripts/generate_seed.py /path/to/Outlier_Paid_Media_Ads.xlsx
"""
import sys
import datetime
import openpyxl

LABELS = {"Narrative", "Audience", "Strategic intent",
          "✓ Proven hook formula", "⚠ Compliance"}


def q(v):
    if v is None or (isinstance(v, str) and not v.strip()):
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (datetime.datetime, datetime.date)):
        return "'" + v.strftime("%Y-%m-%d") + "'"
    return "'" + str(v).strip().replace("'", "''") + "'"


def archetype_of(meta):
    m = (meta or "").lower()
    has_q, has_b = "qualifier" in m, "broad" in m
    if has_q and has_b:
        return "Mixed"
    if has_q:
        return "Qualifier"
    if has_b:
        return "Broad-appeal"
    if "mixed" in m:
        return "Mixed"
    return None


def main(path):
    wb = openpyxl.load_workbook(path, data_only=True)

    # ---- concept families ----
    cf = wb["Concept Families"]
    families, cur = [], None
    for row in cf.iter_rows(values_only=True):
        a = row[0]
        b = row[1] if len(row) > 1 else None
        if a is None or not str(a).strip():
            continue
        a = str(a).strip()
        if a.startswith("Concept Families"):
            continue
        if a in LABELS:
            if not cur:
                continue
            key = a
            if key == "Narrative":
                cur["narrative"] = b
            elif key == "Audience":
                cur["audience"] = b
            elif key == "Strategic intent":
                cur["intent"] = b
            elif key == "✓ Proven hook formula":
                cur["hook"] = b
            elif key == "⚠ Compliance":
                cur["compliance"] = b
        else:
            cur = {"name": a, "meta": b, "narrative": None, "audience": None,
                   "intent": None, "hook": None, "compliance": None}
            families.append(cur)

    # ---- content pieces ----
    cp = wb["Content Pieces"]
    rows = list(cp.iter_rows(values_only=True))
    hdr = [str(h).strip() if h else "" for h in rows[0]]
    idx = {h: i for i, h in enumerate(hdr)}
    creatives = []
    for r in rows[1:]:
        if r[idx["ID"]] is None:
            continue
        creatives.append(r)

    out = []
    out.append("-- AUTO-GENERATED by scripts/generate_seed.py — do not edit by hand.")
    out.append("-- Seeds concept_families + creatives from the Outlier sheet.\n")

    out.append("insert into public.concept_families")
    out.append("  (name, archetype, narrative, audience, strategic_intent, proven_hook_formula, is_proven, compliance_note)")
    out.append("values")
    vals = []
    for f in families:
        is_proven = bool(f["hook"]) or "proven" in (f["meta"] or "").lower()
        vals.append("  (%s, %s, %s, %s, %s, %s, %s, %s)" % (
            q(f["name"]), q(archetype_of(f["meta"])), q(f["narrative"]),
            q(f["audience"]), q(f["intent"]), q(f["hook"]),
            "true" if is_proven else "false", q(f["compliance"]),
        ))
    out.append(",\n".join(vals))
    out.append("on conflict (name) do nothing;\n")

    for r in creatives:
        def g(col):
            i = idx.get(col)
            return r[i] if i is not None else None
        fam = g("Concept Family")
        vd = g("Variant Differentiator")
        is_proven = "proven" in (str(vd or "")).lower()
        out.append(
            "insert into public.creatives\n"
            "  (sheet_id, client_org, concept_family_id, content_summary, hook_line, hook_angle,\n"
            "   archetype, feature_pillar, sport, format, variant_differentiator, cta, is_proven, delivery_date)\n"
            "values (%s, 'Outlier', (select id from public.concept_families where name = %s),\n"
            "   %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)\n"
            "on conflict (sheet_id, client_org) do nothing;" % (
                q(g("ID")), q(fam), q(g("Content Summary")), q(g("Hook Line (first 6s)")),
                q(g("Hook Angle")), q(g("Archetype")), q(g("Feature / Pillar")),
                q(g("Sport / League")), q(g("Format")), q(vd), q(g("Suggested CTA")),
                "true" if is_proven else "false", q(g("Delivery Date")),
            )
        )

    print("\n".join(out))


if __name__ == "__main__":
    main(sys.argv[1])
